version: "3.6"

services:
  db:
    image: postgres:10.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ecoleta-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    image: node:12.13.1-alpine3.9
    command: sh -c "npm install && npm run start"
    working_dir: $PWD
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    environment:
      START_EXPRESS: 1
      APP_NAME: ecoleta-backend
      LOG_LEVEL: debug
      DATABASE_DEBUG: "false"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ecoleta-backend
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_LOGGING: all
      NODE_PATH: Src
    volumes:
      - $PWD:$PWD

volumes:
  postgres:
